import os
import torch

# model
MODEL_NAME = "eva02_large_patch14_448"
NUM_CLASSES = 100

# p1
EPOCHS_PHASE1 = 5
BATCH_SIZE_PHASE1 = 128
NUM_WORKERS_PHASE1 = 8
LR_HEAD_PHASE1 = 1e-3
PATIENCE_PHASE1 = 3

# p2
EPOCHS_PHASE2 = 10
BATCH_SIZE_PHASE2 = 16
NUM_WORKERS_PHASE2 = 4
ACCUM_STEPS = 8
LR_HEAD_PHASE2 = 1e-4
LR_BACKBONE_PHASE2 = 1e-5
PATIENCE_PHASE2 = 5

# p3
EPOCHS_PHASE3 = 10
BATCH_SIZE_PHASE3 = 16
NUM_WORKERS_PHASE3 = 4
ACCUM_STEPS_PHASE3 = 8
LR_HEAD_PHASE3 = 5e-5
LR_BLOCKS_TOP_PHASE3 = 1e-5
LR_BLOCKS_REST_PHASE3 = 1e-6
PATIENCE_PHASE3 = 5

WEIGHT_DECAY = 0.05

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

DATA_DIR = os.environ.get("DATA_DIR", "/content/data")
CKPT = os.environ.get("CKPT_PATH", "best.pth")

WANDB_PROJECT = "cse144-final"
WANDB_ENTITY = os.environ.get("WANDB_ENTITY", "jay_jani-university-of-california")

KAGGLE_COMPETITION = "ucsc-cse-144-spring-2026-final-project"
